name: Auto Publish to Maven Central

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write # Required for publishing packages

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Extract version from commit message
        id: extract_version
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ "$COMMIT_MSG" =~ ^Update\ version\ to\ ([0-9]+\.[0-9]+\.[0-9]+[-a-zA-Z0-9\.]*) ]]; then
            VERSION="${BASH_REMATCH[1]}"
            echo "VERSION=v$VERSION" >> $GITHUB_ENV
          else
            echo "No version update commit found."
            exit 1
          fi

      - name: Update release tag
        run: |
          git tag -f ${{ env.VERSION }}
          git push origin -f ${{ env.VERSION }}

      - name: Publish package
        run: mvn -P release --batch-mode deploy -DskipTests -DperformRelease=true
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
